kind: Service
metadata:
   name: posts
spec:
   containers:
   â€“ name: posts
     image: stephengrider/posts
**
apiVersion: v1
kind: Pod
metadata:
  name: posts
spec:
  containers:
    - name: posts
      image: stephengrider/posts:0.0.1
       